---
Type: "resource_groups"
subscription_id: "4beecc09-f7ae-4469-a36e-dc5106856da2"
subscription_name: "sandbox"
resource_groups:

- name: "resource_group1"
  owner: "vimal.vijayan@essity.com"
  location: "westeurope"
  environment: "dev"
  tags:
  - owner: "vimal"
  - createdBy: "terraform"
  - userstory: "12243"

- name: "resource_group1"
  owner: "vimal.vijayan@essity.com"
  location: "westeurope"
  environment: "stage"
  tags:
  - owner: "vimal"
  - createdBy: "terraform"
  - userstory: "12243"

- name: "resource_group1"
  owner: "vimal.vijayan@essity.com"
  location: "westeurope"
  environment: "prod"
  tags:
  - owner: "vimal"
  - createdBy: "terraform"
  - userstory: "12243"

- name: "resource_group2"
  owner: "vimal.vijayan@essity.com"
  location: "westeurope"
  environment: "prod"
  tags:
  - owner: "vimal"
  - createdBy: "terraform"
  - userstory: "12243"